server:
  port: 8080
#spring:
#  profiles:
#    active: test
dog:
  name: 旺财
  age: 3
#debug: true
spring:
  thymeleaf:
    cache: false
  messages:
    basename: i18n.login
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

# 整合mybatis
mybatis:
  type-aliases-package: com.kuaishou.ljd.model
  mapper-locations: classpath:mybatis/mapper/*.xml
---
server:
  port: 8082
spring:
  profiles: dev

---
server:
  port: 8083
spring:
  profiles: test
